// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ElectroDetali.Models;

public partial class Good
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public decimal? Price { get; set; }

    public int? Categoryid { get; set; }

    public string Image { get; set; }

    public virtual ICollection<Buy> Buys { get; set; } = new List<Buy>();

    public virtual Category Category { get; set; }

    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();
}