// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ElectroDetali.DBModels;

public partial class PickUpPoint
{
    public int Id { get; set; }

    public string Adress { get; set; }

    public int? Time { get; set; }

    public virtual ICollection<Buy> Buys { get; set; } = new List<Buy>();
}